 ---
title: "Nov 22 Data Analysis"
author: "Richard"
date: "November 22, 2018"
output: html_document
---

# Load Data


```{r}
#install.packages("tidyverse")
library(tidyverse)

swallows <- read_csv("Swallows Data Expanded.csv")

swallows <- swallows[,c(139, 1:138, 140:150)]

# Out of 9703 rows, 9608 have SpeciesTotal <= 100, so adjust >100 to 100 for better heatmap
swallows1 <- swallows %>% 
  mutate(SpeciesTotal1 = ifelse(SpeciesTotal > 100, 100, SpeciesTotal))

swallows1 <- swallows1[, c(1, 151, 2:150)]
head(swallows1)

# write_csv(swallows1, "temp.csv")
```

# Make heatmap -- distribution to year

## Draw map of Ontario

Region of observations: Longitude between -95 and -74, Latitude between 42 and 53

```{r}
# install.packages("maps")
# install.packages("mapdata")
library(maps)
library(mapdata)

# Map of the part of Ontario we are interested in
ontario_map1 <- map_data("world", regions = "Canada") %>% 
  filter(long > -95 & long < -74) %>% 
  filter(lat > 42 & lat < 60)

area_map <- ggplot() + 
  geom_polygon(data = ontario_map1, aes(x = long, y = lat, group = group),
               fill = "#F5F5F5", color = "black") + 
  coord_fixed(1.3) 

# Some major Ontario cities
ont_cities <- canada.cities %>% 
  filter(long > -95 & long < -74) %>% 
  filter(lat > 42 & lat < 60) %>% 
  filter(pop > 200000)

ont_cities
```

## Swallows Distribution by years

Note: More routes have been observed between 1994-2015 (i.e. >=75).

```{r}
Swallows_temp <- swallows1 %>%
  filter(Year == 1994, species == "Tree Swallow")

# Generate plot title
Plot_Title <- paste(unique(Swallows_temp$species), "Distribution:", unique(Swallows_temp$Year) )

# Generate plot 
area_map +
  # Add bird distribution data
  geom_point(data = Swallows_temp, aes(x = Longitude, y = Latitude,
                                       size = SpeciesTotal1,
                                       color = SpeciesTotal1,
                                       NULL)) +
  # Add some points (black) for cities
  geom_point(data = ont_cities, aes(x = long, y = lat)) + 
  # Themes
  theme_classic() +
  scale_color_gradient(limits = c(0,100),
                       low = "#FFF15A", high = "Red",
                       name = "Birds Observed at Route"
                       ) +
  scale_size_continuous(limits = c(0, 100), # Range of number observed
                        range = c(1, 3), # Range of size of dots
                        name = "Birds Observed at Route",
                        guide = "none") +

  labs(x = "Longitude", y = "Latitude", title = Plot_Title) +
  theme(axis.text.x = element_text(size = 9, angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        # legend.key.size = unit(0.5, "cm"),
        legend.title = element_text(size = 9),
        NULL) +
  NULL
```

```{r}
for (YearNo in c(1994:2015)) {
  
  Swallows_temp <- swallows1 %>%
  filter(Year == YearNo, species == "Tree Swallow")

  # Generate plot title
  Plot_Title <- paste(unique(Swallows_temp$species), "Distribution:", unique(Swallows_temp$Year) )
  
  # Generate plot 
  plot_temp <- area_map +
    # Add bird distribution data
    geom_point(data = Swallows_temp, aes(x = Longitude, y = Latitude,
                                         size = SpeciesTotal1,
                                         color = SpeciesTotal1,
                                         NULL)) +
    # Add some points (black) for cities
    geom_point(data = ont_cities, aes(x = long, y = lat)) + 
    # Themes
    theme_classic() +
    scale_color_gradient(limits = c(0,100),
                         low = "#FFF15A", high = "Red",
                         name = "Birds Observed at Route"
                         ) +
    scale_size_continuous(limits = c(0, 100), # Range of number observed
                          range = c(1, 3), # Range of size of dots
                          name = "Birds Observed at Route",
                          guide = "none") +
  
    labs(x = "Longitude", y = "Latitude", title = Plot_Title) +
    theme(axis.text.x = element_text(size = 9, angle = 45, hjust = 1),
          plot.title = element_text(hjust = 0.5),
          # legend.key.size = unit(0.5, "cm"),
          legend.title = element_text(size = 9),
          NULL) +
    NULL
  ggsave(paste(unique(Swallows_temp$species), unique(Swallows_temp$Year), ".png"), plot = plot_temp)
}

```

# IDEA to self: gganimate by years
# IDEA: check geom_grid