---
title: "R Notebook"
output: html_notebook
---

Nov 22

#Update on comrades
Richard did a fabulous job creating the master data set. Alex made magnificent weather and other miscellaneous plots. Caroline did some spectacular car plots.

#Other plot ideas: 
- Richard will work on a heat map of swallow distributions
- predation plot/species interaction with potential predators (blue jays, crows)
- how stratum affects swallow abundance

#Statistical tests
- did swallow populations decline? linear regression
- Car_Total effect on swallow abundance
- avg wind, avg temp effect on swallows
- stratum effect on swallows

#Division of Labour
- Richard: heat map
- Alex: linear model looking at avg wind and avg temp effect on swallows - ANOVA
- Caroline: linear model looking at stratum and Car_Total effect on swallows - ANOVA, 
             and did swallow populations decline? - ANOVA

#Other Ideas:
- look at other birds

Note: always plot linear models and explain limitations of data set in report/presentation