---
title: "Project Meeting Nov 1"
author: "R square"
date: "November 1, 2018"
output: html_document
---

# Brainstorming time!

1. Heatmap on bird data?

Let's brainstorm our big hypothesis!

* Note: We can use multiple datasets to support a hypothesis, as long as we are aware of our ambition.

## Species of bird of interest

- Olive-sided Flycatcher (Decline, then recovery effort)
- Bobolinks (Steady decline)
- Loons
- Canada geese

* We might want to look at three different bird species if we don't have enough variables to look through.

## Related species

Swallows: Barn swallow, Cliff swallow, Purple Martin
Goatsuckers: 

## What do we want to look at?

- One species of bird abundance
- Weather (daily weathered trend can be assessed across year)
- Disturbance measured by cars (could be correlational)

# Research question:

**Need to narrow  it down**

What causes the bird abundance to be declining?

# Progress today:

1. Determined that we want to work on birds (can change later)
2. Opened the "extended covariate .csv"
3. Choosing birds to look at.
- Swallows: *Hirudindae* -- Barn Swallow, Cliff Swallow and Purple Martin
    - similar life history, similar trend
    (can look at all of them for now)
    - Need to look at the huge file and filter for Hirudindae.
